### ISSUE TITLE
How to use neptune-gremlin-client via gradle

### ISSUE THREAD

**Issue by samair** [awslabs/amazon-neptune-tools#101]
Is neptune-gremlin-client available to use via Gradle as a dependency?
I looked up and could not find it in   https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-neptune

**Comment by Schachte** [comment]
We're also looking for this @iansrobinson?

**Comment by samair** [comment]
I could do that, but it is a catch-up game, new versions need to be always copied and tracked.

**Comment by beebs-systap** [comment]
Would it be useful to have them published to Maven?

**Comment by samair** [comment]
Yes, they would definitely be useful if available on maven.

**Comment by Schachte** [comment]
@beebs-systap Yes that would be super useful for us!

**Comment by joywa** [comment]
Now published to Maven: https://search.maven.org/artifact/software.amazon.neptune/gremlin-client
