### ISSUE TITLE
Bug on Neptune Export: exception prevents cloned cluster from being deleted

### ISSUE THREAD

**Issue by glevco** [awslabs/amazon-neptune-tools#141]
We are using Neptune Export to generate exports of our graph data. Everything works perfectly most days. The clone cluster gets created, is used, and then is automatically deleted by the tool.

Sometimes, when an internal exception occurs (for example, a connection error), the tool halts and exits without deleting the clone cluster. This causes expensive machines to be kept running until someone manually deletes it. There should be some checks in the tool to perform the deletion in exception scenarios.

Example expected log output when the cluster is correctly deleted:

![Screen Shot 2021-07-09 at 12 11 47](https://user-images.githubusercontent.com/1757957/125100412-70205d80-e0af-11eb-8c39-8a7d294b60aa.png)

Example log output when there's an exception and the cluster is not deleted:

![Screen Shot 2021-07-06 at 13 01 34](https://user-images.githubusercontent.com/1757957/125100503-8e865900-e0af-11eb-83b9-12b7b04bc881.png)

**Comment by beebs-systap** [comment]
@iansrobinson

**Comment by iansrobinson** [comment]
Thanks for reporting this @glevco. Unfortunately, I've not been able to reproduce the issue. If I inject a fault into the export, I nonetheless see the clone being deleted. Do you have any more details you can share?

  - Are you using the latest version of the service from https://docs.aws.amazon.com/neptune/latest/userguide/machine-learning-data-export-service.html or the built jar from https://github.com/awslabs/amazon-neptune-tools/releases/tag/amazon-neptune-tools-1.2, or are you building from source?
  - How are you hosting neptune-export? Some of the lines in the logs include 'Unknown Source', which looks strange to me.

Thanks, ian

**Comment by glevco** [comment]
Hi @iansrobinson, thank you for your response. We'll be checking the version we are running and see if this problem happens again, as I'm also not sure how to reproduce it. I'll close the issue for now, and if it happens again, I'll reopen it. Thanks!
