### ISSUE TITLE
gremlin-client dependency cannot be resolved in maven project

### ISSUE THREAD

**Issue by ValentinTyhonov** [awslabs/amazon-neptune-tools#149]
I'm trying to add gremlin-client dependency to my maven project, but while resolving software.amazon.neptune:gremlin-client:jar:1.0.0 dependency, it's also trying to download software.amazon.neptune:neptune-gremlin-client:pom:1.0.0 from artifactory, which is not exists.

`[ERROR] Failed to execute goal on project ...: Could not resolve dependencies for project ...: Failed to collect dependencies at software.amazon.neptune:gremlin-client:jar:1.0.0: Failed to read artifact descriptor for software.amazon.neptune:gremlin-client:jar:1.0.0: Could not find artifact software.amazon.neptune:neptune-gremlin-client:pom:1.0.0 in maven-central (https://repo1.maven.org/maven2/software) -> [Help 1]`

Any help is appreciated. Thanks.

**Comment by iansrobinson** [comment]
Thank you for reporting this @ValentinTyhonov. Apologies – it's my mistake. I'm in the process of preparing another release to Maven: I'll let you know when that is complete.

**Comment by ValentinTyhonov** [comment]
Thank a lot @iansrobinson. You are doing a great work!

**Comment by ValentinTyhonov** [comment]
It's working. Thank you!
