### ISSUE TITLE
Neptune Export doesn't escape newline character (\n)

### ISSUE THREAD

**Issue by Gabriel-Stofel** [awslabs/amazon-neptune-tools#160]
We are using Neptune Export to generate exports of our graph data and we've noticed recently that it isn't able to escape the newline character `\n`. 

For example, if we were exporting two nodes that had the following properties:
First Node: `{ 'name': ['John\n'], 'country': ['US'] }`
Second Node: `{ 'name': ['James'], 'country': ['UK'] }`

The exported CSV would end up like so (with four lines instead of just three):
name:string,country:string
"John
","US"
"James","UK"

**Comment by iansrobinson** [comment]
Hi @Gabriel-Stofel 

Thanks for reporting this. 

The reason the tool behaves like this is that it exports to the CSV format used by the Neptune bulk loader, which allows for string property values containing newlines. The CSV example you show is in an acceptable bulk load format. If the tool were to escape newline characters, an import into a new Neptune database from an exported CSV file would result in the source and target databases having different contents.

However, I appreciate that some users may want a CSV export format that escapes newline characters. I'll look into adding an option that will force the tool to escape newlines.

ian

**Comment by iansrobinson** [comment]
Hi @Gabriel-Stofel 

I've added an `--escape-newline` command-line switch. (If you're using the Neptune Export service – https://docs.aws.amazon.com/neptune/latest/userguide/machine-learning-data-export-service.html – you can supply a `"escapeNewline": true` field in the `params` object.)

Let me know if you have any issues with this.

Thanks

ian

**Comment by Gabriel-Stofel** [comment]
Hi, @iansrobinson!

Thank you very much for the swift help! I'll close this issue for now, but if I have any problems with this `escapeNewLine` field, I'll reopen it.

Thank you again for all the help!
