### ISSUE TITLE
String representation of dates changed unexpectedly in neptune-export tool

### ISSUE THREAD

**Issue by matthieugrieger** [awslabs/amazon-neptune-tools#164]
Hey there!

My team uses the `neptune-export` JAR for exporting our Neptune database to S3 for further ingestion by other systems. Our ingestion jobs started failing on 2021-09-01 because the format of our timestamp columns changed.

* Format before 2021-09-01: `2021-07-17T19:57:46.063Z`
* Format since 2021-09-01: `Tue Jul 13 03:35:47 UTC 2021`

As far as I know there isn't anything in our codebase that would influence which format is used. I did see that there were some changes related to printing dates as a string on August 31st, not sure if it is related:

https://github.com/awslabs/amazon-neptune-tools/blame/fdff97506b5e5d9bd3a29f4c49dab84622968759/neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/schema/DataType.java#L315-L318

**Comment by beebs-systap** [comment]
@iansrobinson Any ideas?

**Comment by iansrobinson** [comment]
Thanks for reporting that. That sounds like a bug. I’ll look into it.

Kind regards

ian

**Comment by iansrobinson** [comment]
Hi @matthieugrieger 

Apologies - that was my fault. I introduced a regression recently. I've pushed a fix this morning.

Kind regards

ian

**Comment by matthieugrieger** [comment]
No problem, thanks a bunch! I'll check if it's fixed on our end tomorrow. 👍

**Comment by matthieugrieger** [comment]
Just checked our most recent export from Neptune and the timestamps look good now.

Thanks for the quick response! Feel free to close this!
