### ISSUE TITLE
An error occurred while writing all nodes as JSON (Neptune Streams format) to stream.

### ISSUE THREAD

**Issue by carlcelliers-woodside** [awslabs/amazon-neptune-tools#177]
I have ran the export-neptune-to-elasticsearch on two nonprod neptune clusters, dev and a staging, only to keep getting these errors:

An error occurred while writing all nodes as JSON (Neptune Streams format) to stream.
An error occurred while exporting all nodes.
An error occurred while exporting property graph.
and then  multiple of these:
java.util.concurrent.ExecutionException: java.util.concurrent.CompletionException: org.apache.tinkerpop.gremlin.driver.exception.ResponseException: {
    "code": "TimeLimitExceededException",
    "requestId": "f5304c39-0000-0000-0000-000000000000",
    "detailedMessage": "A timeout occurred within the script during evaluation."

The batch job states as completed successfully, however, only 2.2M of the 64M records have been exported into opensearch.

I have modified the neptune_query_timeout parameter timeout to max, 2147483647 but that's made no difference.

Is there anyway to troubleshoot the errors?

**Comment by iansrobinson** [comment]
Hi @carlcelliers-woodside 

This looks like a regular query timeout on the Neptune side. Note that there are both instance-level and cluster-level versions of the neptune_query_timeout parameter: the DB parameter group settings will override the DB cluster parameter group settings. Irrespective of where you set the timeout value (DB parameter group or DB cluster parameter group), you will need to reboot the instances in your cluster for the settings to take effect.

**Comment by carlcelliers-woodside** [comment]
Hi @iansrobinson 
Thank you, that solved the problem. 
I applied the max timeout to db and cluster parameters and rebooted the instances.
