### ISSUE TITLE
Java export command does not return an error code in case of a failure

### ISSUE THREAD

**Issue by dh-nickbilozerov** [awslabs/amazon-neptune-tools#180]
We are using `neptune-export.jar` to run an export job from our AWS Neptune and in case of a failure during an execution command returns `0` code instead of an error code, which makes it quite difficult to track any failures during our pipeline execution.

Ways to reproduce:

Run 
`java -jar neptune-export.jar` for export 

In case of an error, example:
```
An error occurred while creating property graph config. Elapsed time: 32 seconds
java.lang.IllegalStateException: org.apache.tinkerpop.gremlin.process.remote.RemoteConnectionException: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Timed out while waiting for an available host - check the client configuration and connectivity to the server if this message persist 
```

The return code is `0`, I would expect to receive something different since the command has failed.

We are using the latest version - https://s3.amazonaws.com/aws-neptune-customer-samples/neptune-export/bin/neptune-export.jar

**Comment by iansrobinson** [comment]
Hi @dh-nickbilozerov 

Thanks for reporting this. I merged a change this morning that addresses this:

https://github.com/awslabs/amazon-neptune-tools/pull/184

I've also published a fresh version of the jar to https://s3.amazonaws.com/aws-neptune-customer-samples/neptune-export/bin/neptune-export.jar

ian

**Comment by iansrobinson** [comment]
Closing this issue
