### ISSUE TITLE
Retry uploading to S3 only on 5xx error

### ISSUE THREAD

**Issue by asarkar** [awslabs/amazon-neptune-tools#206]
Running from an EC2 instance that doesn't have write access to S3, the script fails to upload the files as expected. However, it keeps retrying, even though this error is non-recoverable. I found 6 instances of the word "Retrying" in the logs in the class `com.amazonaws.services.neptune.export.ExportToS3NeptuneExportEventHandler`.

This ticket is to ask that only 5xx errors be retried.

**Comment by iansrobinson** [comment]
Fixed with #255
