### ISSUE TITLE
Upgrade to gremlin 3.5.2

### ISSUE THREAD

**Issue by khisamutdinov** [awslabs/amazon-neptune-tools#211]
> Starting with [Neptune engine release 1.1.1.0](https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases-1.1.1.0.html) don't use a TinkerPop version lower than 3.5.2.

**Comment by triggan** [comment]
Not sure what this comment is in reference to.  If you're having an issue with one of the utilities in the repo, please provide some additional details.  Closing out this issue for now, but will reopen if further details come to light.
