### ISSUE TITLE
Unable to import module 'kinesis_to_elasticsearch': cannot import name 'W3CNTriplesParser' from 'rdflib.plugins.parsers.ntriples'

### ISSUE THREAD

**Issue by madyanmalfi** [awslabs/amazon-neptune-tools#224]
@gopuneet  When trying to export Neptune to elasticSearch this error shows "`Unable to import module 'kinesis_to_elasticsearch': cannot import name 'W3CNTriplesParser' from 'rdflib.plugins.parsers.ntriples`'". 

After some debugging found out that the lib "rdflib" version 5.0.0  is outdated which does not have "W3CNTriplesParser".

The compiled  file in the template "export-neptune-to-elasticsearch.json" is linked to old compiled zip "neptune-sagemaker/lambda/export-neptune-to-elasticsearch/export-neptune-to-elasticsearch.zip"

**Comment by michaelnchin** [comment]
@madyanmalfi, thank you for the bug report.

We have updated the compiled `export-neptune-to-elasticsearch.zip` S3 file, as referenced in the export-neptune-to-elasticsearch.json template ([here](https://github.com/awslabs/amazon-neptune-tools/blob/master/export-neptune-to-elasticsearch/cloudformation-templates/export-neptune-to-elasticsearch.json#L491)), to use `rdflib==6.1.1`. The same changes are committed to the open source code at #225.
