### ISSUE TITLE
[export-neptune-to-elasticsearch] cannot import name 'builder' from 'google.protobuf.internal'

### ISSUE THREAD

**Issue by xD3CODER** [awslabs/amazon-neptune-tools#226]
When running latest cloudformation template for `export-neptune-to-elasticsearch` I got this error:

```
Runtime.ImportModuleError: Unable to import module 'kinesis_to_elasticsearch': cannot import name 'builder' from 'google.protobuf.internal' (/var/task/google/protobuf/internal/__init__.pyc)
Traceback (most recent call last):
```

**Comment by alfaraak** [comment]
Currently blocked due to this issue as well

**Comment by xD3CODER** [comment]
> 

You can't switch because files were probably compiled with python 3.8

**Comment by triggan** [comment]
This fixed as been deployed and the new lambda packages (with the back-revved aws-kinesis-agg library) have been deployed to all supported regions.
