### ISSUE TITLE
CSV file having URL data 

### ISSUE THREAD

**Issue by chayasree** [awslabs/amazon-neptune-tools#232]
Hello 
My CSV file is having data like http://www.abc.com it is enclosed in double quotes in the file.
But i am getting parsing error while loading into neptune from curl command.
when i try enclosing the string with <> , then there is no error and data is loading but the issue is the '<>' is also loading with the URL.

Does anyone provide solution for this
	curl -X POST -H 'Content-Type: application/json' clustername '
	{
	"source" : "source name",
	"format" : "csv",
	"iamRoleArn" : "<Rolename>",
	"region" : "us-east-1",
	"parallelism" : "MEDIUM",
	"updateSingleCardinalityProperties" : "FALSE",
	"parserConfiguration" : {
    "allowEmptyStrings" : "true"
  },
	"mode":"AUTO", 
	"failOnError":"TRUE",
	"queueRequest" : "TRUE"
	}'

**Comment by triggan** [comment]
@chayasree - Do you mind providing a snippet/sample of the CSV file you're attempting to load so that we may use to test?  Feel free to sanitize ahead of time.

**Comment by chayasree** [comment]
Hi 

Please find the attachments 
[http%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F-14.modified.csv](https://github.com/awslabs/amazon-neptune-tools/files/9137688/http.3A.2F.2Fpurl.org.2Fdc.2Felements.2F1.1.2F-14.modified.csv)
[ADAS-Cog+%28Alzheimer%E2%80%99s+Disease+Assessment+Scale+%E2%80%93+Cognitive+Assessment%29-61532.modified (1).csv](https://github.com/awslabs/amazon-neptune-tools/files/9137690/ADAS-Cog%2B.28Alzheimer.E2.80.99s%2BDisease%2BAssessment%2BScale%2B.E2.80.93%2BCognitive%2BAssessment.29-61532.modified.1.csv)

**Comment by chayasree** [comment]
I have provided 2 different files , which 1st one is not loading and failing with error
second one is loading , but i could not fetch the data with label name

**Comment by triggan** [comment]
It appears as if the first file is not delimited correctly:
```
~id,~label,name:string,vertexType:string,versionLabel:string,versionName:string,seedVersion:int
"126eb6d6-441a-476f-bc54-c6f2c4e34211","http://abc.org/dc/elements/1.1/,Protocol,terminal","CD 2021-03-26","3/26/2021",1
```
The label, name, and versionLabel values are all encapsulated around a single set of `"`.

As you mention, the 2nd file loads successfully.  I'm able to fetch the two related vertices with their label using:
`g.V().hasLabel("ADAS-Cog (Alzheimer’s Disease Assessment Scale – Cognitive Assessment)")`

**Comment by chayasree** [comment]
Hi 

The file got corrupted while i am uploading,

Check this file again
[http%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F-14.modified.csv](https://github.com/awslabs/amazon-neptune-tools/files/9143063/http.3A.2F.2Fpurl.org.2Fdc.2Felements.2F1.1.2F-14.modified.csv)
[http%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F-34741.modified.csv](https://github.com/awslabs/amazon-neptune-tools/files/9143071/http.3A.2F.2Fpurl.org.2Fdc.2Felements.2F1.1.2F-34741.modified.csv)

Please check these 2 files. these 2 files i got error while loading error is : parsing error , reason is : label name cannot be empty.

feeling Very thankful for your response and your time

**Comment by chayasree** [comment]
can u please look into the files i have uploaded once

**Comment by chayasree** [comment]
Hello can u please look into this

**Comment by triggan** [comment]
I'm not seeing the same issue.  Both of those files load correctly:

```
{
  "status": "200 OK",
  "payload": {
    "feedCount": [
      {
        "LOAD_COMPLETED": 2
      }
    ],
    "overallStatus": {
      "fullUri": "s3://<bucket_path_redacted/",
      "runNumber": 1,
      "retryNumber": 0,
      "status": "LOAD_COMPLETED",
      "totalTimeSpent": 3,
      "startTime": 1659667984,
      "totalRecords": 18,
      "totalDuplicates": 0,
      "parsingErrors": 0,
      "datatypeMismatchErrors": 0,
      "insertErrors": 0
    }
  }
}
```

```
g.V().hasLabel('http://abc.org/dc/elements/1.1/').valueMap(true)

[{'vertexType': ['terminal'],
  'versionLabel': ['CD 2021-03-26'],
  <T.label: 4>: 'http://abc.org/dc/elements/1.1/',
  <T.id: 1>: '126eb6d6-441a-476f-bc54-c6f2c4e34211',
  'name': ['Protocol'],
  'versionName': ['3/26/2021'],
  'seedVersion': [1]}]
  ```
  
```
g.V().hasLabel('http://purl.org/dc/elements/1.1').valueMap(true)

[{'vertexType': ['terminology'],
  'versionLabel': ['CT 2021-03-26'],
  <T.label: 4>: 'http://purl.org/dc/elements/1.1',
  <T.id: 1>: '9ddd715b-67c6-4073-bf1a-eb1544aaf0ac',
  'name': ['CDASH'],
  'versionName': ['2021-03-26'],
  'seedVersion': [1]},
 {'vertexType': ['terminology'],
  'versionLabel': ['CT 2021-03-26'],
  <T.label: 4>: 'http://purl.org/dc/elements/1.1',
  <T.id: 1>: '961c2cd6-5bb1-4648-9833-6fac1e8d0ba0',
  'name': ['SDTM'],
  'versionName': ['2021-03-26'],
  'seedVersion': [1]}]
 ```
 
I notice in your load command that you have allowEmptyStrings set to True.  If you use that and you have a row that does not have a label (just ""), then that would throw the parser error that you're seeing above.  As empty strings are not allowed label values.  If you left allowEmptyStrings set to False and supplied no value for a label, Neptune uses a default label name of "vertex" in its place.  You may want to check your load files for any rows that have an empty string ("") in the label field.

Since this is not related to any of the utilities in this repo, I'm going to close this issue.  If you continue to have problems with bulk loading, please make a post to https://repost.aws or open an AWS Support Case and we can continue to work on this issue there.
