### ISSUE TITLE
neptune-export.sh  Unable to access jarfile export-pg

### ISSUE THREAD

**Issue by aharonen** [awslabs/amazon-neptune-tools#24]
Hello,

I was trying to run this command (of course with my Neptune cluster name) bin/neptune-export.sh export-pg -e neptunedbcluster-xxxxxxxxxxxx.cluster-yyyyyyyyyyyy.us-east-1.neptune.amazonaws.com -d  /home/ec2-user/output and I am getting this error message,  **_Unable to access jarfile export-pg_**. 
what I did was to:
1. Clone this project from git to a local directory.
2. Run the command above

Anyone have any idea why I am getting this error?

**Comment by beebs-systap** [comment]
@aharonen Please try running `maven clean install` [(See building)](https://github.com/awslabs/amazon-neptune-tools/tree/master/neptune-export#building-neptune-export), and then retry the neptune-export.sh command.

@iansrobinson

**Comment by iansrobinson** [comment]
@aharonen Were you able successfully to build the command?

**Comment by beebs-systap** [comment]
Closing. Please re-open if the issue persists.

**Comment by Tarvinder91** [comment]
Incase someone still struggling, 'maven clean install' needs to be run from inside the directory: amazon-neptune-tools/neptune-export/
