### ISSUE TITLE
[python-utils] Example for multi-valued properties 

### ISSUE THREAD

**Issue by Bialogs** [awslabs/amazon-neptune-tools#277]
Can you include an example data structure for the `BatchUpload` of vertex with multi-valued properties? 

I am getting confused between what happens within Neptune itself versus what is expected from the `python-utils`. Does the DB parse property strings with `;` or is that handled by a preprocess within these tools?

I am attempting to `BatchUpload` the following:

```
rows = [
    ...
    {"~id": "1234", "~label": "L",  "name:String[]": "Robert;Bob;Rob"}
    ...
]

batch.add_vertices(batch_size=3, rows=rows)
```

The format is translated into the following `GraphTraversal`:

```
[['addV', 'L'], ['property', <T.id: 1>, '1234'], ['property', 'name',  ['Robert', 'Bob', 'Rob']]]
```

However this results in an error:

```
gremlin_python.driver.protocol.GremlinServerError: 499: {"requestId":"rid","code":"UnsupportedOperationException","detailedMessage":"Unsupported property value type: java.util.ArrayList"}
```

**Comment by triggan** [comment]
Thank you for reporting this.  I believe this is a bug here: https://github.com/awslabs/amazon-neptune-tools/blob/d266c838914fb56a1e7c0de5d24464d8ad8a0b7b/neptune-python-utils/neptune_python_utils/batch_utils.py#L52-L53

We should be checking the value to see if it is an Array and then iterating across each element in the Array to create a `property('<key>','<value>')` statement for each value.

**Comment by Bialogs** [comment]
Thank you for checking into this.

For what it's worth defining the problematic property above as `"name:String(set)"` allows the batch upload of multi-valued properties. However, I don't know enough about Neptune to say if `(set)` vs. `[]` are drastically different concepts but they seem the same according to https://docs.aws.amazon.com/neptune/latest/userguide/bulk-load-tutorial-format-gremlin.html

**Comment by iansrobinson** [comment]
Thanks @Bialogs. Looking at the code, I'm thinking that it `"name:String(set)"` is actually resulting in just a single value being inserted – a string with all the values delimited. So it looks like it's working, but it's not.

For sure, there's a bug here. I'll look into it today.

**Comment by iansrobinson** [comment]
@Bialogs and @triggan – Please see: https://github.com/awslabs/amazon-neptune-tools/pull/278
