### ISSUE TITLE
neptune-export compilation error

### ISSUE THREAD

**Issue by elenigen** [awslabs/amazon-neptune-tools#29]
While building with the latest version (41cccfce06648e877672082605dd3590ccb41153), there's a problem with the jackson dependency:

https://github.com/awslabs/amazon-neptune-tools/blob/41cccfce06648e877672082605dd3590ccb41153/neptune-export/pom.xml#L80-L84

In my case, it was retrieving : jackson-core-3.0.0-20190424.231835-446.jar
... where the class `JsonFactory` moved from the package `com.fasterxml.jackson.core` to `com.fasterxml.jackson.core.json`, so it cause this build error:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /git/amazon-neptune-tools/neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/Format.java:[17,34] cannot find symbol
  symbol:   class JsonFactory
  location: package com.fasterxml.jackson.core
[INFO] 1 error
```

To fix it, in my case, I simply forced the version: `<version>2.9.8</version>`

**Comment by beebs-systap** [comment]
@iansrobinson Do you mind taking a quick look at this one?

**Comment by beebs-systap** [comment]
@elenigen Please confirm the latest update works for you.

**Comment by elenigen** [comment]
Still...

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /git/amazon-neptune-tools/neptune-export/src/main/java/com/amazonaws/services/neptune/propertygraph/io/Format.java:[17,34] cannot find symbol
  symbol:   class JsonFactory
  location: package com.fasterxml.jackson.core

```

**Comment by elenigen** [comment]
We just realized this tool is using range() and it's not really reliable when there's a big dataset and there are still write operations, so we won't use this tool.

Thanks anyway,
