### ISSUE TITLE
[glue-neptune] Add batching within each Gremlin Traversal for inserts/upserts to improve throughput

### ISSUE THREAD

**Issue by triggan** [awslabs/amazon-neptune-tools#33]
The current implementation inserts each vertex and edge one at a time along with their properties.  Based on Neptune best practices [1], each Gremlin traversal for inserts/upserts should apply 50-100 objects (an object being a unique vertex, unique edge, and any vertex/edge property) using a single Gremlin traversal.

[1] https://github.com/aws-samples/aws-dbs-refarch-graph/tree/master/src/writing-from-amazon-kinesis-data-streams

**Comment by beebs-systap** [comment]
Closed in https://github.com/awslabs/amazon-neptune-tools/pull/54
