### ISSUE TITLE
Inconsistent indent

### ISSUE THREAD

**Issue by wanchen6** [awslabs/amazon-neptune-tools#4]
Inconsistent indent in this Python graphml2csv.py: tabs and blanks are mixed with each other. This causes failing to run the code.

**Comment by krlawrence** [comment]
I ran into this today as well. The code works fine with Python 2.7 but fails using Python 3.7 with the error below:

```
$ python3 graphml2csv.py -i air-routes-latest.graphml
  File "graphml2csv.py", line 47
    return '{' + ns + '}' + tag
                              ^
TabError: inconsistent use of tabs and spaces in indentation
```

It may be that Python 3 tightened up some code indentation rules perhaps?
