### ISSUE TITLE
Temporary creds expire 

### ISSUE THREAD

**Issue by FitnessTrackerIOS** [awslabs/amazon-neptune-tools#53]
Hi ,

I’m using Neptune python module ( Iam enabled) to load large volume of data multiple times in a single glue job . Looks like credentials are expiring after an hour , can they be refreshed automatically? 

Thanks ,
DInesh k.

**Comment by iansrobinson** [comment]
Hi Dinesh

We'll have to update the IAm auth code to autorefresh - something like this: 

https://dev.to/li_chastina/auto-refresh-aws-tokens-using-iam-role-and-boto3-2cjf

I'll dedicate some time over the next week to incorporating this change.

ian

**Comment by beebs-systap** [comment]
Closed in https://github.com/awslabs/amazon-neptune-tools/pull/54.
