### ISSUE TITLE
neptune-export max-content-length error on default value

### ISSUE THREAD

**Issue by joelsimonoff** [awslabs/amazon-neptune-tools#84]
When running `create-pg-config` I encountered the same `Max frame length` error as described in #68.

```
java.util.concurrent.CompletionException: io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 65536 has been exceeded.
```

It was fixed by setting `--max-content-length 2147483647` as mentioned in #68. Does it make sense to change the default value of `--max-content-length` to avoid this issue? Additionally, what is the best practice for setting this value? When should a lower value such as `65536` be used?

**Comment by iansrobinson** [comment]
Hi @joelsimonoff - thanks for raising this. The default value of 65536 reflects the default value in the underlying Java Gremlin driver. The purpose of this setting is to protect client and server from rogue queries that inadvertently or deliberately attempt to assemble infinitely large messages. While it's perfectly acceptable for the export process to make use of very large messages, I would prefer users of the tool to explicitly acknowledge that their export has an impact on the resources available on the server through setting `--max-content-length` to a larger value.
