### ISSUE TITLE
Unable to pass AWS region for configuring refresh agent based on fetch strategy as GetEndpointsFromNeptuneManagementApi

### ISSUE THREAD

**Issue by kaddybrar** [awslabs/amazon-neptune-tools#96]
Please add a way to pass aws region from the base services using the gremlin-client jar with address fetch strategy as GetEndpointsFromNeptuneManagementApi.
Getting this error :- Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.

Even if we set a local env variable of AWS_REGION, getting the error, so i guess it would be a better thing if we can configure the AmazonNeptuneClient in GetEndpointsFromNeptuneManagementApi's getAddresses method as -> AmazonNeptuneClientBuilder.standard().withRegion(region).build()
Adding PR :- https://github.com/awslabs/amazon-neptune-tools/pull/99

**Comment by iansrobinson** [comment]
Hi @kaddybrar We've recently updated the client to allow you to specify the region when building the cluster (used for signing IAM DB auth queries), and when creating a refresh agent and fetch strategy. You can, for example, now do:

```
GetEndpointsFromNeptuneManagementApi fetchStrategy = new GetEndpointsFromNeptuneManagementApi(
                    clusterId,
                    Collections.singletonList(endpointsSelector),
                    "eu-west-1",
                    profile
            );
```

We've also recently released the Gremlin Client for Amazon Neptune on Maven:

https://search.maven.org/artifact/software.amazon.neptune/gremlin-client
